### ISSUE TITLE
file _motifs_orfonly.fasta and _motifs_orfonly_withM.fasta are empty

### ISSUE THREAD

**Issue by danisabrouk** [fallandar/cysmotifsearcher#1]
Hi,

I would like to use your script on my own data but I can't make it work.
I think it's because the  _motifs_orfonly.fasta and _motifs_orfonly_withM.fasta file are empty but I can't get what are those file ...

**Comment by fallandar** [comment]
Hi.  The file _motifs_orfonly.fasta contains open reading frames including the motifs revealed, and _motifs_orfonly_withM.fasta contains the ORFs from previous file starting from methionine - they supposed to be real ORFs. 

The most probable reason why these files are empty is that Cysmotif searcher has not found any motifs in your input data. 

I have uploaded demo fasta file (demo.fasta) to the repository which contains sequences possessing motifs. Try this file as input data (**cysmotif_searcher.pl -i demo.fasta -m motifs.txt**), and if _motifs_orfonly.fasta still remains empty for your run, let me know and I will investigate this issue further.
