### ISSUE TITLE
Unescaped left brace in regex is deprecated 

### ISSUE THREAD

**Issue by Rusfell** [fallandar/cysmotifsearcher#4]
Hi, when i try to run cysmotif_searcher with: 
`cysmotif_searcher.pl -i demo.fasta -m motifs.txt`

I got error:

> Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.30), passed through in regex; marked by <-- HERE in m/(C[ABD-Z]{2}C[ABD-Z]{7}C[ABD-Z]C[ABD-Z]{ <-- HERE [ABD-Z]}C[ABD-Z]{5}C[ABD-Z]{10}C[ABD-Z]{6}C[ABD-Z]{4}C[ABD-Z]{2}C[ABD-Z]CC)/ at /data/fengyong/software/cysmotifsearcher-master/cysmotif_searcher.pl line 313, <IN> line 33

When I cheched line 33 in the motif.txt:

> DEF24   CX{2}CX{7}CXCX{X}CX{5}CX{10}CX{6}CX{4}CX{2}CXCC

 I found there is a `X ` in `{}`. 
I guess it was the `{X}` caused the error above.

When I replaced X with a random number, cysmotif_searcher succeed.

Is this right?
and which number should i replaced  with?

**Comment by fallandar** [comment]
Hi, thanks for noticing this error. X in brackets in DEF24 is in fact a typo, I have uploaded the corrected motif file - '2' should be in brackets instead of  'X'. I have not encountered this error before, probably, since I used older versions of Perl.
