### ISSUE TITLE
Cysmotif_fasta_cleaner

### ISSUE THREAD

**Issue by Hmn2AP** [fallandar/cysmotifsearcher#5]
Hi

I have been trying to run you csymotif searcher and testing it with the demo file with the command...

cysmotif_searcher.pl -i demo.fasta -m motifs.txt

However, I keep getting 'cysmotif_fasta_cleaner.pl' could not be found and the demo_motifs_final.fasta is empty. The only thing I have edited is the $signalp pathway which I think is running fine. 

I have intentions to test this pipeline of some of out in-house transcript data.
I've not got much of a coding background. Is there something I am missing/doing wrong?

**Comment by fallandar** [comment]
> Hi
> 
> I have been trying to run you csymotif searcher and testing it with the demo file with the command...
> 
> cysmotif_searcher.pl -i demo.fasta -m motifs.txt
> 
> However, I keep getting 'cysmotif_fasta_cleaner.pl' could not be found and the demo_motifs_final.fasta is empty. The only thing I have edited is the $signalp pathway which I think is running fine.
> 
> I have intentions to test this pipeline of some of out in-house transcript data. I've not got much of a coding background. Is there something I am missing/doing wrong?

Hi
Have you cloned the whole repository from github? cysmotif_fasta_cleaner.pl is an auxiliary program that removes duplicated sequences from output fasta file. If it is missing, the results could be empty. 

My guess is that you either have not downloaded 'cysmotif_fasta_cleaner.pl' from github or that it is not executable on your system (it was not set to be executable or it is not located in your PATH/current dir). 

Try running 'cysmotif_fasta_cleaner.pl -h'. If the file cannot be found, check whether such file exists somewhere, and if it does, try setting executable permission on it or move to the same directory as cysmotif_searcher.pl

**Comment by Hmn2AP** [comment]
Thank you for the quick response. I cloned the whole repository, I can see the 'cysmotif_fasta_cleaner.pl' file in the directory. I have just change the permissions to be executable but it still can't seem to run it. 
The -h command  was much help either. 

If it is just removing duplicates does it need to run the cleaner file? I can see results in all the other files, including the demo_motifs_final_tabbed.txt. Which gives me DN12026_c0_g4_i1 as a SNA02. (I am not running SPADA with it)

**Comment by fallandar** [comment]
I suggested running 'cysmotif_fasta_cleaner.pl -h' to check whether it works and can be found in the system. If this command does not produce any results, then there is something wrong with this file.

cysmotif_fasta_cleaner.pl removes sequences which really constitute subsequences of other sequences (e.g., GKCV is a subsequence of ATGKCVRF, and shorter sequence will be removed from final results). It also removes duplicates between SPADA and main module. 

However, the results located in demo_motifs_orfonly_withM.fasta or demo_motifs_final_tabbed.txt are also suitable and can be used, because duplications are usually not that frequent. If you do not use SPADA, you will probably will not see any differences. 

I will probably update the main file to ignore missing  cysmotif_fasta_cleaner.pl in future releases.

**Comment by Hmn2AP** [comment]
Running the 'cysmotif_fasta_cleaner.pl -h' results in this 

chris@chris-Alienware-14:~/Desktop/holly/cysmotifsearcher-master$ cysmotif_fasta_cleaner.pl -h
cysmotif_fasta_cleaner.pl: command not found
chris@chris-Alienware-14:~/Desktop/holly/cysmotifsearcher-master$ perl cysmotif_fasta_cleaner.pl -h
Can't locate cysmotif.pm in @INC (you may need to install the cysmotif module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at cysmotif_fasta_cleaner.pl line 3.
BEGIN failed--compilation aborted at cysmotif_fasta_cleaner.pl line 3.
chris@chris-Alienware-14:~/Desktop/holly/cysmotifsearcher-master$ 

If I can run without it thats fine, I attempted the pipeline on my own transcripts. I am getting results in the 'AP_Pom_motifs_orfonly_withM_signalp_uniq_lt150.fasta' but then the stats are telling me 0 hits matched this criteria, I assume this is due to the lack of results in the final fasta file. Would these results be usable?

**Comment by fallandar** [comment]
Now I see. The module cysmotif.pm should be located in one of the dirs given in your error message. You can create a symbolic link to it in one of this dirs if you have the permissions to do this on your system.

Currently, there is another solution. I have updated cysmotif_fasta_cleaner.pl and now it should take care of this issue.

**Comment by Hmn2AP** [comment]
Ah okay thank. I should be able to get permissions to do so. I will see what I can do. 

Thank you so much for your help

**Comment by fallandar** [comment]
You are welcome. Now you do not need to make a link. Just update the repository and check if the problem persists
